name: coin_talk
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  intl:
  provider: ^6.0.2
  sqflite: ^2.0.2
  http: ^0.13.4
  fl_chart: ^0.41.0
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  chat_bubbles: ^1.2.0

  cupertino_icons: ^1.0.2
  particles_flutter: ^0.1.4
  flutter_particle_bg: ^1.0.4
  theme_provider: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - images/
